### ISSUE TITLE
won't launch.

### ISSUE THREAD

**Issue by brymonster** [CyrisXD/Marlo#1]
I can't seem to get Marlo to open. 
dragged & dropped into Apps folder,
right clicked to open, 
prompted for approval to open app downloaded from internet. 
meanwhile the app shows up in the dock. but once I click 'ok'. it disappears. 
but activity monitor seems to see it still running. can only be 'quit' from activity monitor. 

<img width="532" alt="screen shot 2018-06-25 at 3 40 26 pm" src="https://user-images.githubusercontent.com/12586478/41871890-43532224-788e-11e8-960e-93732e1bedc9.png">
<img width="912" alt="screen shot 2018-06-25 at 3 39 24 pm" src="https://user-images.githubusercontent.com/12586478/41871892-4367e2d6-788e-11e8-8871-db2d7a45e295.png">
<img width="532" alt="screen shot 2018-06-25 at 3 39 05 pm" src="https://user-images.githubusercontent.com/12586478/41871894-437f614a-788e-11e8-9122-bc19ce91a68b.png">

**Comment by CyrisXD** [comment]
It should completely disappear from the dock. But is it not showing at all your MacOS Tray? With the video camera icon.

**Comment by brymonster** [comment]
wow im sorry to waste your time. I was using dark mode for menu and dock. No icon appeared. but it does when you click where it should be! cool thanks.

<img width="163" alt="screen shot 2018-06-25 at 7 48 17 pm" src="https://user-images.githubusercontent.com/12586478/41881322-f1237602-78b0-11e8-94f2-5450db14c2b1.png">
<img width="232" alt="screen shot 2018-06-25 at 7 49 22 pm" src="https://user-images.githubusercontent.com/12586478/41881323-f131d594-78b0-11e8-9d22-1e6b27ff264a.png">

**Comment by CyrisXD** [comment]
No problem at all, I'll need to add this to my to do so if users use Dark Mode it will show a lighter icon. Hopefully available in the next build :) Thank you

**Comment by brymonster** [comment]
yeah no prob. no icon showed at all. it wasn't that it was too dark. 
nice thing. 
thank you!
