### ISSUE TITLE
Live View

### ISSUE THREAD

**Issue by donavanbecker** [CyrisXD/Marlo#2]
Just wondering if it is possible to add live view to the app? Also with dark mode, the app icon in the menu doesn't show.

**Comment by CyrisXD** [comment]
Hi @d0n4v4nb3ck3r, I've had a look into adding a live view but it does not seem possible at this stage. I will try push an updated version as soon as I can. Just dealing with a new born at this stage. But anyone is welcome to do a pull request if they want.

**Comment by donavanbecker** [comment]
@CyrisXD Any luck with this?
